"use strict";
exports.__esModule = true;
var Libros_1 = require("./Libros");
var GestorLibro_1 = require("./GestorLibro");
var biblioteca = new GestorLibro_1.GestorLibros("Biblioteca");
var libro1 = new Libros_1.Libro("John Katzenbach", "El club de los psicópatas", "Drama");
var libro2 = new Libros_1.Libro("John Katzenbach", "La historia del loco", "Drama");
var libro3 = new Libros_1.Libro("John Katzenbach", "El psicoanalista", "Drama");
var libro4 = new Libros_1.Libro("John Katzenbach", "Juicio final", "Drama");
var libro5 = new Libros_1.Libro("John Katzenbach", "Retrato en sangre", "Drama");
var libro6 = new Libros_1.Libro("John Katzenbach", "El profesor", "Drama");
var libro7 = new Libros_1.Libro("John Katzenbach", "Jaque al psicoanalista", "Drama");
var libro8 = new Libros_1.Libro("John Katzenbach", "Un final perfecto", "TerrorPsicologíco");
biblioteca.registrarLibro(libro1);
biblioteca.registrarLibro(libro2);
biblioteca.registrarLibro(libro3);
biblioteca.registrarLibro(libro4);
biblioteca.registrarLibro(libro5);
biblioteca.registrarLibro(libro6);
biblioteca.registrarLibro(libro7);
var arreglo = biblioteca.obtenerLibros();
arreglo.push(libro8);
var biblioteca2 = new GestorLibro_1.GestorLibros("Biblioteca", arreglo);
console.log(biblioteca.toString());
console.log(biblioteca2.toString());
