"use strict";
exports.__esModule = true;
var Futbolista_1 = require("./Futbolista");
var EquipoTecnico_1 = require("./EquipoTecnico");
var EquipoMedico_1 = require("./EquipoMedico");
var SelecionDeFutbol_1 = require("./SelecionDeFutbol");
var fechaDeNacimiento_jugador1 = new Date("06-024-1987");
var fechaDeNacimiento_jugador2 = new Date("06-12-1992");
var fechaDeNacimiento_jugador3 = new Date("03-15-2000");
var fechaDeNacimiento_tecnico1 = new Date("09-30-1980");
var fechaDeNacimiento_tecnico2 = new Date("02-14-1975");
var fechaDeNacimiento_medico1 = new Date("10-12-1979");
var fechaDeNacimiento_medico2 = new Date("1990-01-25");
var jugador1 = new Futbolista_1.Futbolista("Liones", "Messi", 23456798, fechaDeNacimiento_jugador1, 10, "Delantero");
var jugador2 = new Futbolista_1.Futbolista("Lautaro", "Martinez", 23456798, fechaDeNacimiento_jugador2, 9, "Delantero");
var jugador3 = new Futbolista_1.Futbolista("Angel", "Di María", 23456798, fechaDeNacimiento_jugador3, 11, "Delantero");
var listadoFutbolista = [jugador1, jugador2, jugador3];
var cuerpoTecnico1 = new EquipoTecnico_1.EquipoTecnico("Lionel", "Scaloni", 34567898, fechaDeNacimiento_tecnico1, "Técnico");
var cuerpoTecnico2 = new EquipoTecnico_1.EquipoTecnico("Pablo", "Aymar", 34567898, fechaDeNacimiento_tecnico2, "Ayudante de campo");
var listadoEquipoTecnico = [cuerpoTecnico1, cuerpoTecnico2];
var medico1 = new EquipoMedico_1.EquipoMedico("Luis", "García", 23456798, fechaDeNacimiento_medico1, 90856712, "Fisioterapeuta");
var medico2 = new EquipoMedico_1.EquipoMedico("Rodrigo", "Barrios", 29854679, fechaDeNacimiento_medico2, 34567843, "Preparador Físico");
var listadoEquipoMedico = [medico1, medico2];
var seleccionArg = new SelecionDeFutbol_1.SeleccionDeFutbol("Selección Argentina", listadoFutbolista, listadoEquipoTecnico, listadoEquipoMedico);
console.log(seleccionArg);
