"use strict";
exports.__esModule = true;
var CajaDeAhorros_1 = require("./CajaDeAhorros");
var cuentaCorriente_1 = require("./cuentaCorriente");
var persona_1 = require("./persona");
var usuario1 = new persona_1.Persona("Margarita", "Gómez", 34483889);
var cuentaCorriente = new cuentaCorriente_1.CuentaCorriente(usuario1, 34567890312);
var cajaDeAhorros = new CajaDeAhorros_1.CajaDeAhorros(usuario1, 78973321398);
cajaDeAhorros.ingresarSaldo(2000000);
var saldo = cajaDeAhorros.obtenerSaldo();
cajaDeAhorros.ingresarInteres(0.02);
cajaDeAhorros.actualizarSaldo();
console.log(usuario1.toString() + 'Saldo ingresado ' + saldo);
console.log(cajaDeAhorros.toString());
var retiro = cajaDeAhorros.retirar(3000);
cajaDeAhorros.obtenerRetiro();
cajaDeAhorros.actualizarSaldo();
var saldoActualizado = cajaDeAhorros.obtenerSaldo();
console.log('Retiro: ' + retiro + ' \n' + 'En su cuenta quedan: ' + saldoActualizado);
cuentaCorriente.ingresarSaldo(100000);
var saldoCuentaCorriente = cuentaCorriente.obtenerSaldo();
cuentaCorriente.actualizarSaldo();
console.log(usuario1.toString() + 'Saldo ingresado: ' + saldoCuentaCorriente + ' \n ' + cuentaCorriente.toString());
